events {}

http {
    include       mime.types;

    types {
        image/svg+xml svg;
    }

    root /usr/share/nginx/html;

    # 1.svg
    server {
        listen 8081;
        location / {
            try_files /1.svg =404;
            default_type image/svg+xml;
        }
    }

    # 2.svg
    server {
        listen 8082;
        location / {
            try_files /2.svg =404;
            default_type image/svg+xml;
        }
    }

    # 3.svg
    server {
        listen 8083;
        location / {
            try_files /3.svg =404;
            default_type image/svg+xml;
        }
    }

    # 4.svg
    server {
        listen 8084;
        location / {
            try_files /4.svg =404;
            default_type image/svg+xml;
        }
    }

    # Slideshow
    server {
        listen 8085;

        location / {
            index slideshow.html;
        }

        # IMPORTANT: serve SVG correctly here too
        location ~ \.svg$ {
            default_type image/svg+xml;
        }
    }
}
